#!/usr/bin/env ruby
#-*-  Mode:ruby; c-basic-offset:2; tab-width:8; indent-tabs-mode:nil -*-
=begin
  mb-ormapper : O/R Mapper library for iOS/Android
  https://github.com/tmurakam/mb-ormapper

  Copyright (c) 2010-2013, Takuya Murakami. All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer. 

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
=end

ORMDIR = File.expand_path(File.dirname($0))
$LOAD_PATH.push(ORMDIR)

require "orschema.rb"
require 'erb'

VER = "2.1"

def getSqlType(type)
  case type
  when "LONG"
    "INTEGER"
  else
    type
  end
end

def getJavaType(type)
  case type
  when "INTEGER"
    "int"
  when "LONG"
    "long"
  when "REAL"
    "double"
  when "TEXT"
    "String"
  when "DATE"
    "long"
  else
    puts "#{type} is not supported."
    exit 1
  end
end

def getMethodType(type)
  case type
  when "INTEGER"
    "Int"
  when "LONG"
    "Long"
  when "REAL"
    "Double"
  when "TEXT"
    "String"
  when "DATE"
    "Date"
  else
    puts "#{type} not supported"
    exit 1
  end
end

def getToString(type, var)
  case type
  when "INTEGER", "LONG", "REAL"
    return "String.valueOf(#{var})"
  when "TEXT"
    return var
  when "DATE"
    return "ORDatabase.date2str(#{var})"
  else
    puts "#{type} not supported"
    exit 1
  end
end

#
# generate implementation
#
def generateImplementation(cdef, fh)
  erb = ERB.new(File.read(ORMDIR + "/erb-android/implementation.java.erb"), nil, '-')
  fh.puts erb.result(binding)
end

##############################################################
# start from here
deffile = "schema.rb"
if (ARGV.size == 1)
  deffile = ARGV[0]
end

unless File.exist? deffile
  STDERR.puts "no schema file : #{deffile}"
  exit 1
end

# load schema
require deffile

# check vers
unless defined? PKGNAME
  STDERR.puts "You must declare PKGNAME"
  exit 1
end

# primary key name
unless defined? PKEY
  PKEY = "key"
end

# output dir
unless defined? OUTDIR
  OUTDIR = "."
end

# create output dir
outdir = OUTDIR + "/" + PKGNAME.gsub(/\./, "/")
system "mkdir -p " + outdir

# generate
$class_defs.each do |cdef|
  path = outdir + "/" + cdef.base_class_name + ".java"

  STDERR.puts "generate #{path}"
  fh = open(path, "w")
  generateImplementation(cdef, fh)
  fh.close
end
