#!/usr/bin/env ruby
#-*-  Mode:ruby; c-basic-offset:2; tab-width:8; indent-tabs-mode:nil -*-
=begin
  O/R Mapper library for Android

  Copyright (c) 2010-2013, Takuya Murakami. All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer. 

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution. 

  3. Neither the name of the project nor the names of its contributors
  may be used to endorse or promote products derived from this software
  without specific prior written permission. 

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
=end

ORMDIR = File.expand_path(File.dirname($0))
$LOAD_PATH.push(ORMDIR)

require "orschema.rb"
require 'erb'

VER = "1.3"

def getJavaType(type)
  case type
  when "INTEGER"
    return "int";
  when "REAL"
    return "double";
  when "TEXT"
    return "String";
  when "DATE"
    return "long";
  else
    puts "#{type} is not supported."
    exit 1
  end
end

def getMethodType(type)
  case type
  when "INTEGER"
    return "Int"
  when "REAL"
    return "Double"
  when "TEXT"
    return "String"
  when "DATE"
    return "Date"
  else
    puts "#{type} not supported"
    exit 1
  end
end

def getToString(type, var)
  case type
  when "INTEGER"
    return "Integer.toString(#{var})"
  when "REAL"
    return "Double.toString(#{var})"
  when "TEXT"
    return var
  when "DATE"
    return "ORDatabase.date2str(#{var})"
  else
    puts "#{type} not supported"
    exit 1
  end
end


#
# generate implementation
#
def generateImplementation(vers, cdef, fh)
  erb = ERB.new(File.read(ORMDIR + "/erb-android/implementation.java.erb"), nil, '-')
  fh.puts erb.result(binding)
end

##############################################################
# start from here
deffile = "schema.def"
if (ARGV.size == 1)
  deffile = ARGV[0]
end

schema = Schema.new
schema.loadFromFile(deffile)
#schema.dump

# check vers
if (!schema.vers.has_key?("PKGNAME"))
  STDERR.puts "You must declare PKGNAME"
  exit 1
end

# primary key name
if (!schema.vers.has_key?("PKEY"))
  schema.vers["PKEY"] = "key"
end

# output dir
outdir = "."
if (schema.vers.has_key?("OUTDIR"))
  outdir = schema.vers["OUTDIR"]
end

# create output dir
outdir = outdir + "/" + schema.vers["PKGNAME"].gsub(/\./, "/")
system "mkdir -p " + outdir

# generate
schema.defs.each do |cdef|
  path = outdir + "/" + cdef.baseClassName + ".java"

  STDERR.puts "generate #{path}"
  fh = open(path, "w")
  generateImplementation(schema.vers, cdef, fh)
  fh.close
end
